version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.development
    env_file:
      - .env.development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
